// <auto-generated />
using System;
using InventoryManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008065718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and accessories",
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Apparel and fashion items",
                            IsDeleted = false,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Food products and drinks",
                            IsDeleted = false,
                            Name = "Food & Beverages"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Home and office furniture",
                            IsDeleted = false,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Books and publications",
                            IsDeleted = false,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cosmetics and health products",
                            IsDeleted = false,
                            Name = "Beauty & Health"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sports equipment and accessories",
                            IsDeleted = false,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Children's toys and games",
                            IsDeleted = false,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Car and motorcycle accessories",
                            IsDeleted = false,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Home decor and kitchenware",
                            IsDeleted = false,
                            Name = "Home & Living"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("Type");

                    b.HasIndex("ProductId", "TransactionDate");

                    b.HasIndex("WarehouseId", "TransactionDate");

                    b.ToTable("InventoryTransactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 1,
                            Quantity = 50,
                            TotalAmount = 44999.50m,
                            TransactionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 899.99m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 2,
                            Quantity = 30,
                            TotalAmount = 38999.70m,
                            TransactionDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 1299.99m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 3,
                            Quantity = 100,
                            TotalAmount = 8999.00m,
                            TransactionDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 89.99m,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 5,
                            Quantity = 200,
                            TotalAmount = 3998.00m,
                            TransactionDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 19.99m,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 8,
                            Quantity = 120,
                            TotalAmount = 2998.80m,
                            TransactionDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 24.99m,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 11,
                            Quantity = 40,
                            TotalAmount = 7999.60m,
                            TransactionDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 199.99m,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 13,
                            Quantity = 60,
                            TotalAmount = 959.40m,
                            TransactionDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 15.99m,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 15,
                            Quantity = 90,
                            TotalAmount = 3149.10m,
                            TransactionDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 34.99m,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 17,
                            Quantity = 110,
                            TotalAmount = 3298.90m,
                            TransactionDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 29.99m,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            Notes = "Initial stock",
                            ProductId = 19,
                            Quantity = 130,
                            TotalAmount = 5198.70m,
                            TransactionDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1,
                            UnitPrice = 39.99m,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            IsDeleted = false,
                            Notes = "Customer order #1001",
                            ProductId = 1,
                            Quantity = 5,
                            TotalAmount = 4499.95m,
                            TransactionDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            UnitPrice = 899.99m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            IsDeleted = false,
                            Notes = "Customer order #1002",
                            ProductId = 3,
                            Quantity = 15,
                            TotalAmount = 1349.85m,
                            TransactionDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            UnitPrice = 89.99m,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            IsDeleted = false,
                            Notes = "Customer order #1003",
                            ProductId = 5,
                            Quantity = 30,
                            TotalAmount = 599.70m,
                            TransactionDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            UnitPrice = 19.99m,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            IsDeleted = false,
                            Notes = "Customer order #1004",
                            ProductId = 8,
                            Quantity = 10,
                            TotalAmount = 249.90m,
                            TransactionDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            UnitPrice = 24.99m,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            IsDeleted = false,
                            Notes = "Customer order #1005",
                            ProductId = 11,
                            Quantity = 3,
                            TotalAmount = 599.97m,
                            TransactionDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2,
                            UnitPrice = 199.99m,
                            WarehouseId = 3
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MinimumStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6.7 inch OLED, 128GB storage, 8GB RAM",
                            IsDeleted = false,
                            MinimumStockThreshold = 10,
                            Name = "Smartphone X Pro",
                            Price = 899.99m,
                            SKU = "PHN-001",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "14 inch, Intel i7, 16GB RAM, 512GB SSD",
                            IsDeleted = false,
                            MinimumStockThreshold = 5,
                            Name = "Laptop UltraBook Z",
                            Price = 1299.99m,
                            SKU = "LAP-001",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bluetooth 5.2, noise canceling, IPX5 water resistant",
                            IsDeleted = false,
                            MinimumStockThreshold = 20,
                            Name = "Wireless Earbuds",
                            Price = 89.99m,
                            SKU = "AUD-001",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GPS, heart rate monitor, sleep tracking",
                            IsDeleted = false,
                            MinimumStockThreshold = 15,
                            Name = "Smartwatch S5",
                            Price = 249.99m,
                            SKU = "WCH-001",
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% cotton, slim fit, various colors",
                            IsDeleted = false,
                            MinimumStockThreshold = 30,
                            Name = "Classic T-Shirt",
                            Price = 19.99m,
                            SKU = "CLT-001",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Straight cut, 98% cotton 2% elastane",
                            IsDeleted = false,
                            MinimumStockThreshold = 20,
                            Name = "Denim Jeans",
                            Price = 49.99m,
                            SKU = "CLT-002",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Waterproof, insulated, removable hood",
                            IsDeleted = false,
                            MinimumStockThreshold = 10,
                            Name = "Winter Jacket",
                            Price = 89.99m,
                            SKU = "CLT-003",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arabica blend, medium roast, 1kg package",
                            IsDeleted = false,
                            MinimumStockThreshold = 25,
                            Name = "Premium Coffee Beans",
                            Price = 24.99m,
                            SKU = "FOD-001",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "50 tea bags, organic certified",
                            IsDeleted = false,
                            MinimumStockThreshold = 40,
                            Name = "Organic Green Tea",
                            Price = 12.99m,
                            SKU = "FOD-002",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "70% cocoa, fair trade",
                            IsDeleted = false,
                            MinimumStockThreshold = 50,
                            Name = "Dark Chocolate Bar",
                            Price = 4.99m,
                            SKU = "FOD-003",
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic, height adjustable, lumbar support",
                            IsDeleted = false,
                            MinimumStockThreshold = 5,
                            Name = "Office Chair",
                            Price = 199.99m,
                            SKU = "FRN-001",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wooden dining table, seats 6 people",
                            IsDeleted = false,
                            MinimumStockThreshold = 5,
                            Name = "Dining Table",
                            Price = 349.99m,
                            SKU = "FRN-002",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bestseller fiction, 400 pages",
                            IsDeleted = false,
                            MinimumStockThreshold = 10,
                            Name = "The Great Novel",
                            Price = 15.99m,
                            SKU = "BOK-001",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "500 recipes, full color photography",
                            IsDeleted = false,
                            MinimumStockThreshold = 8,
                            Name = "Cooking Guide",
                            Price = 29.99m,
                            SKU = "BOK-002",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "50ml, moisturizing, anti-aging",
                            IsDeleted = false,
                            MinimumStockThreshold = 15,
                            Name = "Organic Face Cream",
                            Price = 34.99m,
                            SKU = "BTH-001",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "30ml, 20% vitamin C, hyaluronic acid",
                            IsDeleted = false,
                            MinimumStockThreshold = 10,
                            Name = "Vitamin C Serum",
                            Price = 44.99m,
                            SKU = "BTH-002",
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official size 7, rubber exterior",
                            IsDeleted = false,
                            MinimumStockThreshold = 20,
                            Name = "Basketball",
                            Price = 29.99m,
                            SKU = "SPT-001",
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight, cushioned sole, breathable mesh",
                            IsDeleted = false,
                            MinimumStockThreshold = 15,
                            Name = "Running Shoes",
                            Price = 79.99m,
                            SKU = "SPT-002",
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "200 pieces, compatible with major brands",
                            IsDeleted = false,
                            MinimumStockThreshold = 25,
                            Name = "Building Blocks Set",
                            Price = 39.99m,
                            SKU = "TOY-001",
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12 inch doll with accessories",
                            IsDeleted = false,
                            MinimumStockThreshold = 15,
                            Name = "Doll Playset",
                            Price = 49.99m,
                            SKU = "TOY-002",
                            StockQuantity = 85
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@inventory.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$0hdhguLaQ/ChcFqXUnqL5u21QIVRAXRkebMZy/FBJqWMAM.V4Blcy",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@inventory.com",
                            FullName = "Regular User",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$Rc0hTySIZnnB8s/PBQzZGehZk7MHm.xqGkuLHa70WoDNsA25xUise",
                            Role = 1,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentOccupancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1000,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 0,
                            IsDeleted = false,
                            Location = "Jakarta, Indonesia",
                            Name = "Main Warehouse"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 500,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 0,
                            IsDeleted = false,
                            Location = "Bandung, Indonesia",
                            Name = "Secondary Warehouse"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 750,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 0,
                            IsDeleted = false,
                            Location = "Surabaya, Indonesia",
                            Name = "Surabaya Warehouse"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 400,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 0,
                            IsDeleted = false,
                            Location = "Medan, Indonesia",
                            Name = "Medan Warehouse"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 600,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentOccupancy = 0,
                            IsDeleted = false,
                            Location = "Makassar, Indonesia",
                            Name = "Makassar Warehouse"
                        });
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Entities.User", "CreatedByUser")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Domain.Entities.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagement.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("InventoryManagement.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("InventoryManagement.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("InventoryTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
